# --- Binds ---
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Use vi keybindings in Copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# pane resizing w/ key repeat
bind-key -r J resize-pane -D 10
bind-key -r K resize-pane -U 10
bind-key -r H resize-pane -L 10
bind-key -r L resize-pane -R 10

# Bind movement between panes
bind h select-pane -L  
bind j select-pane -D  
bind k select-pane -U  
bind l select-pane -R 

# Rebind switch to last window
bind i last-window  

# Split panes using b and v
bind-key v split-window -h
bind-key b split-window -v
unbind-key '"'
unbind-key %

# Don't confirm killing panes and windows
bind-key x kill-pane
bind-key X kill-window
unbind-key &

# --- Terminal ---
setw -g xterm-keys on
set -s escape-time 0                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on

set -g history-limit 5000                 # boost history

# --- Colors & Theme ---
# Colors
BACKGROUND=default
FOREGROUND="#ebdbb2"
HIGHLIGHT="#d65d0e"
ACTIVITY="#a0d0f0"

# Title
set -g set-titles on
set -g set-titles-string '#(whoami)@#H - (#S:#W.#P)'

# Panes
set -g pane-border-style fg=default
set -g pane-active-border-style fg=$HIGHLIGHT,bg=default

set -g display-panes-time 1000
set -g display-panes-colour $FOREGROUND
set -g display-panes-active-colour $HIGHLIGHT

# Clock
set -g clock-mode-colour $FOREGROUND
set -g clock-mode-style 24

# Mode
set -g mode-style bg=$HIGHLIGHT,fg=$BACKGROUND

# Windows

setw -g window-status-format " #I:#W"
setw -g window-status-style bg=default,fg=$FOREGROUND,dim
setw -g window-status-last-style fg=$FOREGROUND,bold

setw -g window-status-current-format " #I:#W"
setw -g window-status-current-style bg=default,fg=$HIGHLIGHT,bold

setw -g window-status-activity-style bg=$BACKGROUND,fg=$ACTIVITY,dim

# Base index ( start counting from 1 )
set -g base-index 1
setw -g pane-base-index 1

# Status Top
set -g status-position top

# Status Colors
set -g status-style fg=$FOREGROUND,bg=$BACKGROUND

# Status Interval
# But there is a strange bug that freezes osx
# https://github.com/tmux/tmux/issues/108
# set to 0
set -g status-interval 0

# Status contents
set -g status-left ' λ '
set -g status-right "#(uptime | sed -e 's/.* up //g; s/,.*$//') | #S"

# Message
set -g message-style fg=$HIGHLIGHT,bg=$BACKGROUND,bright



# --- Tmux Plugin Manager ---

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'kitty'

# for neovim
set -g @resurrect-strategy-nvim 'session'

# --- sessionx ---
set -g @sessionx-bind 'o'
set -g @sessionx-prefix on
set -g @sessionx-x-path '~/projects'
set -g @sessionx-fzf-builtin-tmux 'off'
set -g @sessionx-zoxide-mode 'off'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
