# Custom Kitty config
#
# --- Fonts ---
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12

# --- Scrollback ---
scrollback_lines 3000

# --- Performances ---
repaint_delay 5

# --- Audio ---
enable_audio_bell no

# --- URL ---
url_color #83a598
url_style dashed

# --- Window ---
window_margin_width 10
window_padding_width 5

# --- Colors ---
include ~/.config/kitty/kitty_gruvbox_theme/gruvbox_dark_soft.conf

# --- Editor ---
editor vim
