# i3blocks config file

# Define global properties
separator_block_width=20
markup=pango

# Date & Time
[date]
command=date '+%a %d %b %Y %H:%M'
interval=10

# Weather (example, requires internet connection and external script)
#[weather]
#command=~/.config/i3/scripts/weather.sh
#interval=1000
#color=#8ec07c

# CPU Usage
[cpu]
command=echo  $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {printf " %.1f%", usage}')
interval=5
color=#cc241d

# RAM Usage
[memory]
command=free -h | awk '/Mem:/ {raw_usage=$3; usage_percentage=($3/$2)*100; printf "  %.1fGi (%.1f%%)", raw_usage, usage_percentage}'
interval=10
color=#98971a

# Disk Space
[disk]
command=df -h --output=source,size,used,avail / | awk 'NR==2 {raw_usage=$3; usage_percentage=($3/$2)*100; printf " %.1f Gi (%.1f%%)", raw_usage, usage_percentage}'
interval=60
color=#d79921

# Battery Monitoring
[battery]
command=~/.config/i3/scripts/battery_status.sh
interval=30
color=#b16286

# Network Manager
[network_status]
command=~/.config/i3/scripts/network_status.sh 
interval=10
label=

